'use strict';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;};
let token=location.hash.slice(1)||sessionStorage.getItem('xyro-token')||'';
if(token){sessionStorage.setItem('xyro-token',token);history.replaceState(null,'',location.pathname);}
let info=null,current=null,report=null,profile='recon',view='scan',findingLimit=100,assetLimit=150,polling=false,selected=new Set(),previewCoverage=null,taskLimit=100;
const statuses={queued:'В очереди',running:'Выполняется',completed:'Завершено',partial:'Частичные результаты',cancelled:'Остановлено',interrupted:'Прервано',error:'Ошибка',missing:'Нет модуля',timeout:'Лимит времени',skipped:'Пропущено'};
const severityNames={critical:'Критические',high:'Высокие',medium:'Средние',low:'Низкие',info:'Информация'};
const verificationNames={pending:'Ожидает повторной проверки',reproduced:'Повторно воспроизведено',not_reproduced:'При повторе не воспроизведено',not_applicable:'Повторная проверка недоступна',context_required:'Нужен контекст приложения',error:'Ошибка перепроверки'};
const viewNames={coverage:['Покрытие и агенты','План проверок, ограничения и работа исполнителей.'],scan:['Обзор проверки','От поиска активов до проверяемых находок.'],findings:['Находки','Приоритет, доказательства и рекомендации.'],assets:['Карта активов','Домены, сервисы, технологии, URL и параметры.'],history:['История проверок','Результаты сохраняются на этом устройстве.'],tools:['Инструменты и шаблоны','Одинаковый состав на Android и ПК.']};
function error(message){$('error').textContent=message||'';$('error').hidden=!message;}
async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){let reason='Ошибка '+r.status;try{reason=(await r.json()).error||reason;}catch{}throw Error(reason);}return r.json();}
function showView(name){view=name;document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!=='view-'+name);document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('view-title').textContent=viewNames[name][0];$('view-subtitle').textContent=viewNames[name][1];if(name==='history')loadHistory().catch(e=>error(e.message));if(name==='findings')renderFindings();if(name==='assets')renderAssets();if(name==='coverage')renderCoverage();}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
function selectProfile(name){profile=name;selected=new Set(info.profiles[name]);document.querySelectorAll('.profile').forEach(x=>x.classList.toggle('selected',x.dataset.profile===name));document.querySelectorAll('#module-picker input').forEach(x=>x.checked=selected.has(x.value));$('selected-count').textContent=selected.size;$('profile-hint').textContent={quick:'Проверка доступности, технологий и шаблонов Nuclei.',recon:'Поддомены, сервисы, URL, технологии и открытые пути.',audit:'Разведка, Nuclei, служебные файлы, параметры, XSS и SQLi. Полнота зависит от времени и доступности цели.'}[name];if(name==='quick')$('nuclei_preset').value='fast';else $('nuclei_preset').value=name==='audit'?'all':'balanced';}
document.querySelectorAll('.profile').forEach(b=>b.addEventListener('click',()=>{if(info)selectProfile(b.dataset.profile);}));
function config(){const data={target:$('target').value.trim(),targets:$('targets').value,profile,tools:[...selected],include_subdomains:$('include_subdomains').checked,ports:$('ports').value,exclude_paths:$('exclude_paths').value,custom_paths:$('custom_paths').value,headers:$('headers').value,nuclei_preset:$('nuclei_preset').value,nuclei_ids:$('nuclei_ids').value,nuclei_severities:[...document.querySelectorAll('#nuclei-severities input:checked')].map(x=>x.value)};for(const k of ['rps','stage_timeout','depth','max_urls','max_hosts','concurrency','agents','verify_limit','censys_pages'])data[k]=Number($(k).value);for(const k of ['agent_mode','censys_token','censys_org','oast_server','oast_token','requests','auth_headers_b','auth_urls','auth_marker'])data[k]=$(k).value;for(const k of ['intrusive','include_weak','extended_protocols','oast_enabled','scan_forms'])data[k]=$(k).checked;data.categories=[...document.querySelectorAll('#category-picker input:checked')].map(x=>x.value);return data;}
$('scan-form').addEventListener('submit',async e=>{e.preventDefault();error('');$('start').disabled=true;try{const r=await api('/api/jobs',config());current=r.id;report=null;previewCoverage=null;await poll();if(innerWidth<1200)document.querySelector('.progress-panel').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){error(e.message);$('start').disabled=false;}});
$('cancel').addEventListener('click',async()=>{try{await api('/api/cancel/'+current,{});$('cancel').disabled=true;$('coverage-note').textContent='Останавливаем текущий этап и сохраняем результаты…';}catch(e){error(e.message);}});
$('resume').addEventListener('click',async()=>{try{await api('/api/resume/'+current,{stage_timeout:Number($('stage_timeout').value)});await poll();}catch(e){error(e.message);}});
$('export').addEventListener('click',async()=>{if(!current)return;try{if(window.AndroidExport){window.AndroidExport.save(current);return;}const r=await fetch('/api/export/'+current,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Не удалось подготовить отчёт');const blob=await r.blob(),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='XYRO-'+current+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){error(e.message);}});
$('show-findings').addEventListener('click',()=>showView('findings'));
function elapsed(row){const seconds=Math.max(0,Math.floor((row.finished||Date.now()/1000)-row.created));return `${Math.floor(seconds/3600)?Math.floor(seconds/3600)+':':''}${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
async function poll(){if(!current||polling)return;polling=true;try{report=await api('/api/job/'+current);renderReport();}catch(e){error(e.message);}finally{polling=false;}}
function renderReport(){const r=report;if(!r)return;const busy=['queued','running'].includes(r.status);$('start').disabled=busy;$('cancel').disabled=!busy;$('export').disabled=false;$('resume').hidden=!['partial','cancelled','interrupted','error'].includes(r.status);$('scan-target').textContent=r.target;$('status').textContent=(statuses[r.status]||r.status).toUpperCase();$('coverage-note').textContent=r.status==='partial'?'Часть этапов не завершена. Открой журнал или продолжи проверку.':r.status==='completed'?'Все выбранные этапы завершены. Отсутствие находок не доказывает безопасность сайта.':busy?'Результаты появляются по мере выполнения. Остановленная проверка сохраняет уже найденные данные.':r.interruption||'Результаты сохранены. Продолжение повторит незавершённые этапы; Nuclei и Arjun учитывают сохранённый прогресс.';
const assets=r.assets||[];$('metric-findings').textContent=r.findings.length;$('metric-urls').textContent=r.urls.length;$('metric-hosts').textContent=new Set(assets.map(a=>a.host).filter(Boolean)).size||new Set(r.urls.map(u=>{try{return new URL(u).hostname;}catch{return '';}})).size;$('nav-findings').textContent=r.findings.length;$('nav-assets').textContent=assets.length;$('elapsed').textContent=elapsed(r);const pipeline=r.pipeline||r.config.tools||info.profiles[r.config.profile],done=r.stages.filter(s=>!['running','queued'].includes(s.status)).length;$('progress-fill').style.width=(pipeline.length?100*done/pipeline.length:0)+'%';$('stage-caption').textContent=`Этапы: ${done} / ${pipeline.length}`;$('agents-state').textContent=r.agents?`Агенты: ${r.agents.active||0} активны / ${r.agents.workers} исполнителей · задачи: ${(r.tasks||[]).filter(t=>t.status==='completed').length} / ${(r.tasks||[]).length}`:'Агенты ожидают задания.';
const root=$('stages');root.replaceChildren();for(const tool of pipeline){const s=r.stages.find(s=>s.tool===tool),row=el('div',undefined,'stage '+(s?.status||'waiting'));row.append(el('span',s?.status==='completed'?'✓':s?.status==='running'?'●':s&&['error','missing','timeout'].includes(s.status)?'!':'○','symbol'));const label=el('div');label.append(el('span',tool));let sub=info.labels[tool];if(s?.templates_total!==undefined)sub+=` · ${s.templates_done||0} / ${s.templates_total} шаблонов`;if(s?.targets_total!==undefined)sub+=` · ${s.targets_done||0} / ${s.targets_total} адресов`;if(s?.reused)sub+=' · из предыдущего запуска';if(s?.detail)sub=s.detail;label.append(el('small',sub));const btn=el('button',s?statuses[s.status]||s.status:'Ожидает');btn.disabled=!s;btn.addEventListener('click',()=>showLog(tool,s));row.append(label,btn);root.append(row);}
const recent=$('recent-findings');recent.replaceChildren();recent.className='';for(const f of r.findings.slice(-4).reverse())recent.append(findingRow(f));if(!r.findings.length)recent.append(el('p','Находок пока нет.','empty'));if(view==='findings')renderFindings();if(view==='assets')renderAssets();if(view==='coverage'&&!previewCoverage)renderCoverage();}
function findingRow(f){const row=el('button',undefined,'finding'),text=el('span');text.append(el('b',f.title),el('small',f.url));row.append(el('span',f.severity,'level '+f.severity),text,el('span',f.tool,'tool'));row.addEventListener('click',()=>showFinding(f));return row;}
function renderFindings(){const counts=$('severity-stats');counts.replaceChildren();for(const [s,label] of Object.entries(severityNames)){const box=el('div',undefined,'stat-card');box.append(el('strong',(report?.findings||[]).filter(f=>f.severity===s).length),el('small',label));counts.append(box);}const q=$('finding-search').value.toLowerCase(),severity=$('severity-filter').value,tool=$('tool-filter').value;const rows=(report?.findings||[]).filter(f=>(severity==='all'||f.severity===severity)&&(tool==='all'||f.tool===tool)&&JSON.stringify(f).toLowerCase().includes(q)).sort((a,b)=>Object.keys(severityNames).indexOf(a.severity)-Object.keys(severityNames).indexOf(b.severity));const root=$('findings-list');root.replaceChildren();rows.slice(0,findingLimit).forEach(f=>root.append(findingRow(f)));if(!rows.length)root.append(el('p',report?'По выбранным фильтрам находок нет.':'Сначала запусти или открой проверку.','empty'));$('more-findings').hidden=rows.length<=findingLimit;}
function assetDescription(a){if(a.kind==='dns')return a.record+' → '+(a.values||[]).join(' · ');if(a.kind==='web')return [a.status,a.title,(a.technologies||[]).join(', '),a.server].filter(Boolean).join(' · ');if(a.kind==='service')return a.transport+' / '+a.status;if(a.kind==='tls')return `${a.protocol} · ${a.cipher} · ${a.days_left} дней до истечения`;if(a.kind==='domain')return (a.in_scope?'В активной области':'Только инвентаризация')+' · '+a.source;if(a.kind==='osint')return a.address+' · '+a.detail;if(a.kind==='form')return a.method+' '+a.action+' · '+(a.fields||[]).join(', ');if(a.kind==='parameter')return 'Параметр '+a.name+' · '+a.source;return [a.status,a.source,a.size?`${a.size} символов`:null].filter(Boolean).join(' · ');}
function renderAssets(){const q=$('asset-search').value.toLowerCase(),kind=$('asset-filter').value,rows=(report?.assets||[]).filter(a=>(kind==='all'||a.kind===kind)&&JSON.stringify(a).toLowerCase().includes(q));$('asset-count').textContent=`Активов: ${rows.length}. Пассивно найденный домен или архивный URL не означает доступный сервис.`;const root=$('asset-list');root.replaceChildren();for(const a of rows.slice(0,assetLimit)){const row=el('div',undefined,'asset-row'),text=el('div');text.append(el('strong',a.url||a.host||a.key),el('small',assetDescription(a)));row.append(el('span',a.kind,'asset-kind'),text);root.append(row);}if(!rows.length)root.append(el('p','Активы появятся по мере выполнения recon.','empty'));$('more-assets').hidden=rows.length<=assetLimit;}
function detail(title){$('detail-title').textContent=title;$('detail-content').replaceChildren();$('detail').showModal();return $('detail-content');}
function item(root,label,value){if(value===undefined||value===null||value==='')return;root.append(el('div',label,'detail-label'),el('div',Array.isArray(value)?value.join(', '):value,'detail-value'));}
function showFinding(f){const root=detail(f.title);root.append(el('span',f.severity,'level '+f.severity));item(root,'Модуль',f.tool);item(root,'URL',f.url);item(root,'Статус доказательства',f.confidence);item(root,'Перепроверка',verificationNames[f.verification]||'Не выполнялась');item(root,'Категории',(f.categories||[]).map(k=>info.categories[k]||k));item(root,'Предупреждение upstream',f.upstream_warning);item(root,'Шаблон',f.template_id);item(root,'Путь шаблона',f.template_path);item(root,'CVE',f.cve);item(root,'CWE',f.cwe);item(root,'CVSS',f.cvss);item(root,'Данные детектора',f.evidence);item(root,'Рекомендация',f.remediation);if(f.references?.length){root.append(el('div','Источники','detail-label'));for(const url of [].concat(f.references)){if(/^https?:\/\//.test(url)){const a=el('a',url,'reference');a.href=url;a.target='_blank';a.rel='noopener noreferrer';root.append(a);}}}const copy=el('button','Копировать URL','secondary');copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(f.url);copy.textContent='Скопировано';}catch{copy.textContent='Выдели URL выше';}});root.append(copy);}
async function showLog(tool,stage){const root=detail(tool+' · '+(statuses[stage.status]||stage.status));if(stage.error)item(root,'Причина',stage.error);item(root,'Бюджет этапа',stage.budget?stage.budget+' сек.':null);if(stage.templates_total!==undefined)item(root,'Завершено шаблонов',`${stage.templates_done||0} / ${stage.templates_total}`);if(stage.targets_total!==undefined)item(root,'Завершено адресов',`${stage.targets_done||0} / ${stage.targets_total}`);item(root,'Текущий адрес',stage.current_target);try{const data=await api('/api/log/'+current+'/'+tool);root.append(el('pre',data.text));}catch(e){root.append(el('p',e.message));}}
$('close-detail').addEventListener('click',()=>$('detail').close());$('detail').addEventListener('click',e=>{if(e.target===$('detail'))$('detail').close();});
for(const id of ['finding-search','severity-filter','tool-filter'])$(id).addEventListener('input',()=>{findingLimit=100;renderFindings();});for(const id of ['asset-search','asset-filter'])$(id).addEventListener('input',()=>{assetLimit=150;renderAssets();});$('more-findings').addEventListener('click',()=>{findingLimit+=100;renderFindings();});$('more-assets').addEventListener('click',()=>{assetLimit+=150;renderAssets();});
async function loadHistory(){const rows=await api('/api/jobs'),root=$('history-list');root.replaceChildren();for(const row of rows){const button=el('button',undefined,'history-item'),label=el('span');label.append(el('strong',row.target),el('small',new Date(row.created*1000).toLocaleString('ru-RU')));button.append(label,el('small',statuses[row.status]||row.status));button.addEventListener('click',async()=>{current=row.id;previewCoverage=null;await poll();showView('scan');});root.append(button);}if(!rows.length)root.append(el('p','История пока пуста.','empty'));}
$('refresh-history').addEventListener('click',()=>loadHistory().catch(e=>error(e.message)));
async function init(){info=await api('/api/info');const entries=Object.entries(info.tools),ready=entries.filter(([,v])=>v.ready).length;$('health').textContent=`${ready} / ${entries.length} МОДУЛЕЙ`;$('platform').textContent=info.platform.toUpperCase()+' · '+info.version;const root=$('tool-list'),picker=$('module-picker');for(const [name,label] of Object.entries(info.labels)){const v=info.tools[name],row=el('div',undefined,'tool-item'),box=el('span');box.append(el('strong',name),el('small',label));row.append(box,el('span',v.ready?'ГОТОВ':'НЕ УСТАНОВЛЕН',v.ready?'ready':'missing'));root.append(row);const choice=el('label',undefined,'check'),check=el('input');check.type='checkbox';check.value=name;check.addEventListener('change',()=>{check.checked?selected.add(name):selected.delete(name);profile='custom';document.querySelectorAll('.profile').forEach(x=>x.classList.remove('selected'));$('selected-count').textContent=selected.size;$('profile-hint').textContent='Свой набор модулей: '+selected.size;});choice.append(check,el('span',name+' · '+label));picker.append(choice);const option=el('option',name);option.value=name;$('tool-filter').append(option);}for(const [name,label] of Object.entries(severityNames)){const choice=el('label',undefined,'check'),check=el('input');check.type='checkbox';check.value=name;check.checked=true;choice.append(check,el('span',name));$('nuclei-severities').append(choice);}const templates=info.tools.nuclei?.templates;if(templates?.count){$('template-info').textContent=`${templates.count.toLocaleString('ru-RU')} шаблонов в каталоге · DAST: ${templates.groups?.dast||0}, SSL: ${templates.groups?.ssl||0} · снимок ${templates.snapshot_date}`;$('template-details').textContent=`Nuclei Templates ${templates.upstream_release}: ${templates.count} записей каталога. Commit ${templates.commit}. Снимок ${templates.snapshot_date}. DAST CVE: ${(templates.dast_years||[]).join(', ')}. Шаблоны исполняются пакетами по 32 с сохранением прогресса. Headless требует Chromium и не включён в исполнение этой сборки.`;}else{$('template-info').textContent='База шаблонов не включена в эту сборку.';}initCategories();selectProfile('recon');const jobs=await api('/api/jobs');if(jobs.length){current=jobs[0].id;await poll();}setInterval(()=>{if(report&&['running','queued'].includes(report.status))poll();},2000);}
function initCategories(){for(const [key,label] of Object.entries(info.categories)){const row=el('label',undefined,'check'),check=el('input');check.type='checkbox';check.value=key;check.checked=true;row.append(check,el('span',label));$('category-picker').append(row);}}
function renderCoverage(){const rows=previewCoverage||report?.coverage||[],root=$('coverage-list');root.replaceChildren();$('coverage-source').textContent=previewCoverage?'ПРЕДВАРИТЕЛЬНЫЙ ПЛАН':'ТЕКУЩАЯ ПРОВЕРКА';for(const c of rows){const row=el('div',undefined,'coverage-row');row.append(el('b',c.label),el('span',`Выбрано ${c.selected} / ${c.catalog}`));const reasons=Object.entries(c.reasons||{}).map(([label,count])=>`${label}: ${count}`).join(' · ');row.append(el('small',reasons||'Все шаблоны категории выбраны; выполнение см. в задачах.'));root.append(row);}if(!rows.length)root.append(el('p','Открой проверку или посмотри план перед запуском.','empty'));const tasks=report?.tasks||[],list=$('task-list');list.replaceChildren();for(const t of tasks.slice(0,taskLimit)){const row=el('div',undefined,'task-row');row.append(el('b',t.tool+' · '+(statuses[t.status]||t.status)),el('small',`${t.targets.length} адресов · ${t.templates_done||0} / ${t.templates_total||0} шаблонов${t.reused?' · сохранённый результат':''}`),el('small',t.targets.join(' · ')));if(t.error||t.detail)row.append(el('small',t.error||t.detail));list.append(row);}if(!tasks.length)list.append(el('p','Задачи появятся после запуска.','empty'));$('more-tasks').hidden=tasks.length<=taskLimit;}
$('more-tasks').addEventListener('click',()=>{taskLimit+=100;renderCoverage();});
$('preview-plan').addEventListener('click',async()=>{try{error('');const data=await api('/api/plan',config());previewCoverage=data.coverage;showView('coverage');}catch(e){error(e.message);}});
$('request-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>4*1024*1024)throw Error('Файл должен быть меньше 4 MiB');const raw=JSON.parse(await file.text());let rows=raw;if(raw.log?.entries){rows=raw.log.entries.map(entry=>entry.request).filter(Boolean).map(r=>({method:r.method,url:r.url,headers:Object.fromEntries((r.headers||[]).filter(h=>!['host','content-length','transfer-encoding','connection','proxy-authorization','proxy-connection'].includes(h.name.toLowerCase())&&!h.name.startsWith(':')).map(h=>[h.name,h.value])),body:r.postData?.text||''}));}if(!Array.isArray(rows)||rows.length>100)throw Error('Ожидается до 100 запросов; экспортируй нужные записи HAR.');$('requests').value=JSON.stringify(rows,null,2);error('');}catch(e){error('Импорт: '+e.message);}});
init().catch(e=>error('Не удалось подключиться к локальному ядру: '+e.message));
